
!------------------------------------------------------------------------!
!  The Community Multiscale Air Quality (CMAQ) system software is in     !
!  continuous development by various groups and is based on information  !
!  from these groups: Federal Government employees, contractors working  !
!  within a United States Government contract, and non-Federal sources   !
!  including research institutions.  These groups give the Government    !
!  permission to use, prepare derivative works of, and distribute copies !
!  of their work in the CMAQ system to the public and to permit others   !
!  to do so.  The United States Environmental Protection Agency          !
!  therefore grants similar permission to use the CMAQ system software,  !
!  but users are requested to provide copies of derivative works or      !
!  products designed to operate in the CMAQ system to the United States  !
!  Government without restrictions as to use by others.  Software        !
!  that is used with the CMAQ system but distributed under the GNU       !
!  General Public License or the GNU Lesser General Public License is    !
!  subject to their copyright restrictions.                              !
!------------------------------------------------------------------------!
 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE aqchem_Parameters

  USE aqchem_Precision
  PUBLIC
  SAVE


! TOTAL_SPECIES - Total Number of species
  INTEGER, PARAMETER :: TOTAL_SPECIES = 156 
! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 156 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 153 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 102 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 3 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 200 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 154 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 429 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 430 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 154 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 156 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_A_NO3AKN = 1 
  INTEGER, PARAMETER :: ind_A_NH4AKN = 2 
  INTEGER, PARAMETER :: ind_A_CLAKN = 3 
  INTEGER, PARAMETER :: ind_A_NAAKN = 4 
  INTEGER, PARAMETER :: ind_A_SO4AKN = 5 
  INTEGER, PARAMETER :: ind_A_PECAKN = 6 
  INTEGER, PARAMETER :: ind_A_POAAKN = 7 
  INTEGER, PARAMETER :: ind_A_PRIAKN = 8 
  INTEGER, PARAMETER :: ind_L_PRIACC = 9 
  INTEGER, PARAMETER :: ind_L_PECACC = 10 
  INTEGER, PARAMETER :: ind_L_POAACC = 11 
  INTEGER, PARAMETER :: ind_L_FEPLUS3 = 12 
  INTEGER, PARAMETER :: ind_L_MNPLUS2 = 13 
  INTEGER, PARAMETER :: ind_L_CAPLUS2 = 14 
  INTEGER, PARAMETER :: ind_L_MGPLUS2 = 15 
  INTEGER, PARAMETER :: ind_L_KPLUS = 16 
  INTEGER, PARAMETER :: ind_L_NAPLUS = 17 
  INTEGER, PARAMETER :: ind_WD_SO2 = 18 
  INTEGER, PARAMETER :: ind_WD_HNO3 = 19 
  INTEGER, PARAMETER :: ind_WD_CO2 = 20 
  INTEGER, PARAMETER :: ind_WD_NH4OH = 21 
  INTEGER, PARAMETER :: ind_WD_H2O2 = 22 
  INTEGER, PARAMETER :: ind_WD_O3 = 23 
  INTEGER, PARAMETER :: ind_WD_HCOOH = 24 
  INTEGER, PARAMETER :: ind_WD_MHP = 25 
  INTEGER, PARAMETER :: ind_WD_PAA = 26 
  INTEGER, PARAMETER :: ind_WD_H2SO4 = 27 
  INTEGER, PARAMETER :: ind_WD_HCL = 28 
  INTEGER, PARAMETER :: ind_WD_GLY = 29 
  INTEGER, PARAMETER :: ind_WD_MGLY = 30 
  INTEGER, PARAMETER :: ind_WD_NO3MIN = 31 
  INTEGER, PARAMETER :: ind_WD_NH4PLUS = 32 
  INTEGER, PARAMETER :: ind_WD_CLMIN = 33 
  INTEGER, PARAMETER :: ind_WD_PRIACC = 34 
  INTEGER, PARAMETER :: ind_WD_FEPLUS3 = 35 
  INTEGER, PARAMETER :: ind_WD_MNPLUS2 = 36 
  INTEGER, PARAMETER :: ind_WD_PECACC = 37 
  INTEGER, PARAMETER :: ind_WD_ORGC = 38 
  INTEGER, PARAMETER :: ind_L_ORGC = 39 
  INTEGER, PARAMETER :: ind_WD_POAACC = 40 
  INTEGER, PARAMETER :: ind_WD_HPLUS = 41 
  INTEGER, PARAMETER :: ind_WD_CAPLUS2 = 42 
  INTEGER, PARAMETER :: ind_WD_MGPLUS2 = 43 
  INTEGER, PARAMETER :: ind_WD_KPLUS = 44 
  INTEGER, PARAMETER :: ind_WD_NAPLUS = 45 
  INTEGER, PARAMETER :: ind_WD_ISOPND = 46 
  INTEGER, PARAMETER :: ind_WD_ISOPNB = 47 
  INTEGER, PARAMETER :: ind_WD_MVKN = 48 
  INTEGER, PARAMETER :: ind_WD_MACRN = 49 
  INTEGER, PARAMETER :: ind_WD_DHDN = 50 
  INTEGER, PARAMETER :: ind_WD_IMONIT = 51 
  INTEGER, PARAMETER :: ind_WD_UTONIT = 52 
  INTEGER, PARAMETER :: ind_WD_UTONIN = 53 
  INTEGER, PARAMETER :: ind_WD_TONIT = 54 
  INTEGER, PARAMETER :: ind_WD_TONIN = 55 
  INTEGER, PARAMETER :: ind_WD_TONIH = 56 
  INTEGER, PARAMETER :: ind_WD_HONIT = 57 
  INTEGER, PARAMETER :: ind_WD_INHEDB = 58 
  INTEGER, PARAMETER :: ind_WD_IHPN = 59 
  INTEGER, PARAMETER :: ind_WD_IHDPN = 60 
  INTEGER, PARAMETER :: ind_WD_IDHPN = 61 
  INTEGER, PARAMETER :: ind_WD_R4N = 62 
  INTEGER, PARAMETER :: ind_WD_R4NO = 63 
  INTEGER, PARAMETER :: ind_WD_INPD = 64 
  INTEGER, PARAMETER :: ind_WD_INPB = 65 
  INTEGER, PARAMETER :: ind_WD_IHND = 66 
  INTEGER, PARAMETER :: ind_WD_IHNB = 67 
  INTEGER, PARAMETER :: ind_WD_ISNP = 68 
  INTEGER, PARAMETER :: ind_WD_MTHYD = 69 
  INTEGER, PARAMETER :: ind_L_MTHYD = 70 
  INTEGER, PARAMETER :: ind_G_IDHPN = 71 
  INTEGER, PARAMETER :: ind_L_IDHPN = 72 
  INTEGER, PARAMETER :: ind_G_R4NO = 73 
  INTEGER, PARAMETER :: ind_L_R4NO = 74 
  INTEGER, PARAMETER :: ind_G_INPB = 75 
  INTEGER, PARAMETER :: ind_L_INPB = 76 
  INTEGER, PARAMETER :: ind_G_IHNB = 77 
  INTEGER, PARAMETER :: ind_L_IHNB = 78 
  INTEGER, PARAMETER :: ind_G_R4N = 79 
  INTEGER, PARAMETER :: ind_L_R4N = 80 
  INTEGER, PARAMETER :: ind_G_INPD = 81 
  INTEGER, PARAMETER :: ind_L_INPD = 82 
  INTEGER, PARAMETER :: ind_G_IHND = 83 
  INTEGER, PARAMETER :: ind_L_IHND = 84 
  INTEGER, PARAMETER :: ind_G_ISNP = 85 
  INTEGER, PARAMETER :: ind_L_ISNP = 86 
  INTEGER, PARAMETER :: ind_G_IHDPN = 87 
  INTEGER, PARAMETER :: ind_L_IHDPN = 88 
  INTEGER, PARAMETER :: ind_G_O3 = 89 
  INTEGER, PARAMETER :: ind_G_HCOOH = 90 
  INTEGER, PARAMETER :: ind_G_MHP = 91 
  INTEGER, PARAMETER :: ind_L_GLY = 92 
  INTEGER, PARAMETER :: ind_G_GLY = 93 
  INTEGER, PARAMETER :: ind_L_MGLY = 94 
  INTEGER, PARAMETER :: ind_G_MGLY = 95 
  INTEGER, PARAMETER :: ind_G_PAA = 96 
  INTEGER, PARAMETER :: ind_G_HCL = 97 
  INTEGER, PARAMETER :: ind_G_SO2 = 98 
  INTEGER, PARAMETER :: ind_G_HNO3 = 99 
  INTEGER, PARAMETER :: ind_G_CO2 = 100 
  INTEGER, PARAMETER :: ind_G_NH3 = 101 
  INTEGER, PARAMETER :: ind_G_H2O2 = 102 
  INTEGER, PARAMETER :: ind_G_ISOPND = 103 
  INTEGER, PARAMETER :: ind_L_ISOPND = 104 
  INTEGER, PARAMETER :: ind_G_ISOPNB = 105 
  INTEGER, PARAMETER :: ind_L_ISOPNB = 106 
  INTEGER, PARAMETER :: ind_G_MVKN = 107 
  INTEGER, PARAMETER :: ind_L_MVKN = 108 
  INTEGER, PARAMETER :: ind_G_MACRN = 109 
  INTEGER, PARAMETER :: ind_L_MACRN = 110 
  INTEGER, PARAMETER :: ind_G_DHDN = 111 
  INTEGER, PARAMETER :: ind_L_DHDN = 112 
  INTEGER, PARAMETER :: ind_G_IMONIT = 113 
  INTEGER, PARAMETER :: ind_L_IMONIT = 114 
  INTEGER, PARAMETER :: ind_G_UTONIT = 115 
  INTEGER, PARAMETER :: ind_L_UTONIT = 116 
  INTEGER, PARAMETER :: ind_G_UTONIN = 117 
  INTEGER, PARAMETER :: ind_L_UTONIN = 118 
  INTEGER, PARAMETER :: ind_G_TONIT = 119 
  INTEGER, PARAMETER :: ind_L_TONIT = 120 
  INTEGER, PARAMETER :: ind_G_TONIN = 121 
  INTEGER, PARAMETER :: ind_L_TONIN = 122 
  INTEGER, PARAMETER :: ind_G_TONIH = 123 
  INTEGER, PARAMETER :: ind_L_TONIH = 124 
  INTEGER, PARAMETER :: ind_G_HONIT = 125 
  INTEGER, PARAMETER :: ind_L_HONIT = 126 
  INTEGER, PARAMETER :: ind_G_INHEDB = 127 
  INTEGER, PARAMETER :: ind_L_INHEDB = 128 
  INTEGER, PARAMETER :: ind_G_IHPN = 129 
  INTEGER, PARAMETER :: ind_L_IHPN = 130 
  INTEGER, PARAMETER :: ind_L_CO3MIN2 = 131 
  INTEGER, PARAMETER :: ind_L_HCO3MIN = 132 
  INTEGER, PARAMETER :: ind_L_H2CO3 = 133 
  INTEGER, PARAMETER :: ind_L_HCOOMIN = 134 
  INTEGER, PARAMETER :: ind_L_HCOOH = 135 
  INTEGER, PARAMETER :: ind_L_HCL = 136 
  INTEGER, PARAMETER :: ind_L_CLMIN = 137 
  INTEGER, PARAMETER :: ind_L_NO3MIN = 138 
  INTEGER, PARAMETER :: ind_L_HNO3 = 139 
  INTEGER, PARAMETER :: ind_L_NH4OH = 140 
  INTEGER, PARAMETER :: ind_L_NH4PLUS = 141 
  INTEGER, PARAMETER :: ind_L_OHMIN = 142 
  INTEGER, PARAMETER :: ind_L_H2SO4 = 143 
  INTEGER, PARAMETER :: ind_L_HSO4MIN = 144 
  INTEGER, PARAMETER :: ind_L_MHP = 145 
  INTEGER, PARAMETER :: ind_L_H2O2 = 146 
  INTEGER, PARAMETER :: ind_L_SO4MIN2 = 147 
  INTEGER, PARAMETER :: ind_L_PAA = 148 
  INTEGER, PARAMETER :: ind_L_SO2 = 149 
  INTEGER, PARAMETER :: ind_L_SO3MIN2 = 150 
  INTEGER, PARAMETER :: ind_L_HSO3MIN = 151 
  INTEGER, PARAMETER :: ind_L_HPLUS = 152 
  INTEGER, PARAMETER :: ind_L_O3 = 153 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_L_H2O = 154 
  INTEGER, PARAMETER :: ind_L_HO = 155 
  INTEGER, PARAMETER :: ind_DUMMY = 156 

! Index declaration for dummy species


! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_L_H2O = 1 
  INTEGER, PARAMETER :: indf_L_HO = 2 
  INTEGER, PARAMETER :: indf_DUMMY = 3 

! Index declaration for mechanism species

  INTEGER, PARAMETER :: spc_ind_G_SO2 = 1 
  INTEGER, PARAMETER :: spc_ind_G_HNO3 = 2 
  INTEGER, PARAMETER :: spc_ind_G_CO2 = 3 
  INTEGER, PARAMETER :: spc_ind_G_NH3 = 4 
  INTEGER, PARAMETER :: spc_ind_G_H2O2 = 5 
  INTEGER, PARAMETER :: spc_ind_G_O3 = 6 
  INTEGER, PARAMETER :: spc_ind_G_HCOOH = 7 
  INTEGER, PARAMETER :: spc_ind_G_MHP = 8 
  INTEGER, PARAMETER :: spc_ind_G_PAA = 9 
  INTEGER, PARAMETER :: spc_ind_G_HCL = 10 
  INTEGER, PARAMETER :: spc_ind_G_GLY = 11 
  INTEGER, PARAMETER :: spc_ind_G_MGLY = 12 
  INTEGER, PARAMETER :: spc_ind_A_NO3AKN = 13 
  INTEGER, PARAMETER :: spc_ind_A_NH4AKN = 14 
  INTEGER, PARAMETER :: spc_ind_A_CLAKN = 15 
  INTEGER, PARAMETER :: spc_ind_A_NAAKN = 16 
  INTEGER, PARAMETER :: spc_ind_A_SO4AKN = 17 
  INTEGER, PARAMETER :: spc_ind_A_PECAKN = 18 
  INTEGER, PARAMETER :: spc_ind_A_POAAKN = 19 
  INTEGER, PARAMETER :: spc_ind_A_PRIAKN = 20 
  INTEGER, PARAMETER :: spc_ind_L_SO2 = 21 
  INTEGER, PARAMETER :: spc_ind_L_HNO3 = 22 
  INTEGER, PARAMETER :: spc_ind_L_H2CO3 = 23 
  INTEGER, PARAMETER :: spc_ind_L_NH4OH = 24 
  INTEGER, PARAMETER :: spc_ind_L_H2O2 = 25 
  INTEGER, PARAMETER :: spc_ind_L_O3 = 26 
  INTEGER, PARAMETER :: spc_ind_L_HCOOH = 27 
  INTEGER, PARAMETER :: spc_ind_L_MHP = 28 
  INTEGER, PARAMETER :: spc_ind_L_PAA = 29 
  INTEGER, PARAMETER :: spc_ind_L_H2SO4 = 30 
  INTEGER, PARAMETER :: spc_ind_L_HCL = 31 
  INTEGER, PARAMETER :: spc_ind_L_GLY = 32 
  INTEGER, PARAMETER :: spc_ind_L_MGLY = 33 
  INTEGER, PARAMETER :: spc_ind_L_SO4MIN2 = 34 
  INTEGER, PARAMETER :: spc_ind_L_NO3MIN = 35 
  INTEGER, PARAMETER :: spc_ind_L_NH4PLUS = 36 
  INTEGER, PARAMETER :: spc_ind_L_CLMIN = 37 
  INTEGER, PARAMETER :: spc_ind_L_PRIACC = 38 
  INTEGER, PARAMETER :: spc_ind_L_PECACC = 39 
  INTEGER, PARAMETER :: spc_ind_L_ORGC = 40 
  INTEGER, PARAMETER :: spc_ind_L_POAACC = 41 
  INTEGER, PARAMETER :: spc_ind_L_HPLUS = 42 
  INTEGER, PARAMETER :: spc_ind_L_OHMIN = 43 
  INTEGER, PARAMETER :: spc_ind_L_FEPLUS3 = 44 
  INTEGER, PARAMETER :: spc_ind_L_MNPLUS2 = 45 
  INTEGER, PARAMETER :: spc_ind_L_HSO3MIN = 46 
  INTEGER, PARAMETER :: spc_ind_L_SO3MIN2 = 47 
  INTEGER, PARAMETER :: spc_ind_L_HCO3MIN = 48 
  INTEGER, PARAMETER :: spc_ind_L_CO3MIN2 = 49 
  INTEGER, PARAMETER :: spc_ind_L_HCOOMIN = 50 
  INTEGER, PARAMETER :: spc_ind_L_HSO4MIN = 51 
  INTEGER, PARAMETER :: spc_ind_L_CAPLUS2 = 52 
  INTEGER, PARAMETER :: spc_ind_L_MGPLUS2 = 53 
  INTEGER, PARAMETER :: spc_ind_L_KPLUS = 54 
  INTEGER, PARAMETER :: spc_ind_L_NAPLUS = 55 
  INTEGER, PARAMETER :: spc_ind_WD_SO2 = 56 
  INTEGER, PARAMETER :: spc_ind_WD_HNO3 = 57 
  INTEGER, PARAMETER :: spc_ind_WD_CO2 = 58 
  INTEGER, PARAMETER :: spc_ind_WD_NH4OH = 59 
  INTEGER, PARAMETER :: spc_ind_WD_H2O2 = 60 
  INTEGER, PARAMETER :: spc_ind_WD_O3 = 61 
  INTEGER, PARAMETER :: spc_ind_WD_HCOOH = 62 
  INTEGER, PARAMETER :: spc_ind_WD_MHP = 63 
  INTEGER, PARAMETER :: spc_ind_WD_PAA = 64 
  INTEGER, PARAMETER :: spc_ind_WD_H2SO4 = 65 
  INTEGER, PARAMETER :: spc_ind_WD_HCL = 66 
  INTEGER, PARAMETER :: spc_ind_WD_GLY = 67 
  INTEGER, PARAMETER :: spc_ind_WD_MGLY = 68 
  INTEGER, PARAMETER :: spc_ind_WD_NO3MIN = 69 
  INTEGER, PARAMETER :: spc_ind_WD_NH4PLUS = 70 
  INTEGER, PARAMETER :: spc_ind_WD_CLMIN = 71 
  INTEGER, PARAMETER :: spc_ind_WD_PRIACC = 72 
  INTEGER, PARAMETER :: spc_ind_WD_FEPLUS3 = 73 
  INTEGER, PARAMETER :: spc_ind_WD_MNPLUS2 = 74 
  INTEGER, PARAMETER :: spc_ind_WD_PECACC = 75 
  INTEGER, PARAMETER :: spc_ind_WD_ORGC = 76 
  INTEGER, PARAMETER :: spc_ind_WD_POAACC = 77 
  INTEGER, PARAMETER :: spc_ind_WD_HPLUS = 78 
  INTEGER, PARAMETER :: spc_ind_WD_CAPLUS2 = 79 
  INTEGER, PARAMETER :: spc_ind_WD_MGPLUS2 = 80 
  INTEGER, PARAMETER :: spc_ind_WD_KPLUS = 81 
  INTEGER, PARAMETER :: spc_ind_WD_NAPLUS = 82 
  INTEGER, PARAMETER :: spc_ind_G_ISOPND = 83 
  INTEGER, PARAMETER :: spc_ind_G_ISOPNB = 84 
  INTEGER, PARAMETER :: spc_ind_G_MVKN = 85 
  INTEGER, PARAMETER :: spc_ind_G_MACRN = 86 
  INTEGER, PARAMETER :: spc_ind_G_DHDN = 87 
  INTEGER, PARAMETER :: spc_ind_G_IMONIT = 88 
  INTEGER, PARAMETER :: spc_ind_G_UTONIT = 89 
  INTEGER, PARAMETER :: spc_ind_G_UTONIN = 90 
  INTEGER, PARAMETER :: spc_ind_G_TONIT = 91 
  INTEGER, PARAMETER :: spc_ind_G_TONIN = 92 
  INTEGER, PARAMETER :: spc_ind_G_TONIH = 93 
  INTEGER, PARAMETER :: spc_ind_G_HONIT = 94 
  INTEGER, PARAMETER :: spc_ind_G_INHEDB = 95 
  INTEGER, PARAMETER :: spc_ind_G_IHPN = 96 
  INTEGER, PARAMETER :: spc_ind_G_IHDPN = 97 
  INTEGER, PARAMETER :: spc_ind_G_IDHPN = 98 
  INTEGER, PARAMETER :: spc_ind_G_R4N = 99 
  INTEGER, PARAMETER :: spc_ind_G_R4NO = 100 
  INTEGER, PARAMETER :: spc_ind_G_INPD = 101 
  INTEGER, PARAMETER :: spc_ind_G_INPB = 102 
  INTEGER, PARAMETER :: spc_ind_G_IHND = 103 
  INTEGER, PARAMETER :: spc_ind_G_IHNB = 104 
  INTEGER, PARAMETER :: spc_ind_G_ISNP = 105 
  INTEGER, PARAMETER :: spc_ind_L_ISOPND = 106 
  INTEGER, PARAMETER :: spc_ind_L_ISOPNB = 107 
  INTEGER, PARAMETER :: spc_ind_L_MVKN = 108 
  INTEGER, PARAMETER :: spc_ind_L_MACRN = 109 
  INTEGER, PARAMETER :: spc_ind_L_DHDN = 110 
  INTEGER, PARAMETER :: spc_ind_L_IMONIT = 111 
  INTEGER, PARAMETER :: spc_ind_L_UTONIT = 112 
  INTEGER, PARAMETER :: spc_ind_L_UTONIN = 113 
  INTEGER, PARAMETER :: spc_ind_L_TONIT = 114 
  INTEGER, PARAMETER :: spc_ind_L_TONIN = 115 
  INTEGER, PARAMETER :: spc_ind_L_TONIH = 116 
  INTEGER, PARAMETER :: spc_ind_L_HONIT = 117 
  INTEGER, PARAMETER :: spc_ind_L_INHEDB = 118 
  INTEGER, PARAMETER :: spc_ind_L_IHPN = 119 
  INTEGER, PARAMETER :: spc_ind_L_IHDPN = 120 
  INTEGER, PARAMETER :: spc_ind_L_IDHPN = 121 
  INTEGER, PARAMETER :: spc_ind_L_R4N = 122 
  INTEGER, PARAMETER :: spc_ind_L_R4NO = 123 
  INTEGER, PARAMETER :: spc_ind_L_INPD = 124 
  INTEGER, PARAMETER :: spc_ind_L_INPB = 125 
  INTEGER, PARAMETER :: spc_ind_L_IHND = 126 
  INTEGER, PARAMETER :: spc_ind_L_IHNB = 127 
  INTEGER, PARAMETER :: spc_ind_L_ISNP = 128 
  INTEGER, PARAMETER :: spc_ind_L_MTHYD = 129 
  INTEGER, PARAMETER :: spc_ind_WD_ISOPND = 130 
  INTEGER, PARAMETER :: spc_ind_WD_ISOPNB = 131 
  INTEGER, PARAMETER :: spc_ind_WD_MVKN = 132 
  INTEGER, PARAMETER :: spc_ind_WD_MACRN = 133 
  INTEGER, PARAMETER :: spc_ind_WD_DHDN = 134 
  INTEGER, PARAMETER :: spc_ind_WD_IMONIT = 135 
  INTEGER, PARAMETER :: spc_ind_WD_UTONIT = 136 
  INTEGER, PARAMETER :: spc_ind_WD_UTONIN = 137 
  INTEGER, PARAMETER :: spc_ind_WD_TONIT = 138 
  INTEGER, PARAMETER :: spc_ind_WD_TONIN = 139 
  INTEGER, PARAMETER :: spc_ind_WD_TONIH = 140 
  INTEGER, PARAMETER :: spc_ind_WD_HONIT = 141 
  INTEGER, PARAMETER :: spc_ind_WD_INHEDB = 142 
  INTEGER, PARAMETER :: spc_ind_WD_IHPN = 143 
  INTEGER, PARAMETER :: spc_ind_WD_IHDPN = 144 
  INTEGER, PARAMETER :: spc_ind_WD_IDHPN = 145 
  INTEGER, PARAMETER :: spc_ind_WD_R4N = 146 
  INTEGER, PARAMETER :: spc_ind_WD_R4NO = 147 
  INTEGER, PARAMETER :: spc_ind_WD_INPD = 148 
  INTEGER, PARAMETER :: spc_ind_WD_INPB = 149 
  INTEGER, PARAMETER :: spc_ind_WD_IHND = 150 
  INTEGER, PARAMETER :: spc_ind_WD_IHNB = 151 
  INTEGER, PARAMETER :: spc_ind_WD_ISNP = 152 
  INTEGER, PARAMETER :: spc_ind_WD_MTHYD = 153 
  INTEGER, PARAMETER :: spc_ind_L_H2O = 154 
  INTEGER, PARAMETER :: spc_ind_L_HO = 155 
  INTEGER, PARAMETER :: spc_ind_DUMMY = 156 

END MODULE aqchem_Parameters

